### ISSUE TITLE
Enable Booking the Appointment when a person enters mobile number

### ISSUE THREAD

**Issue by panickervinod** [oah-health/oah-health#16]
On the reception area landing page of the Digital clinic

Enable Booking the Appointment when a person enters a valid mobile number. If the profile exists ask for the pin else book appointment as a new users

**Comment by secretsayan** [comment]
*Enable Booking the Appointment when a person enters a valid mobile number -- this part has been done.

**Comment by secretsayan** [comment]
Also there is no pin to be asked for returning users...as there is no pin ever set as authentication pin in the login flow. Hence closing this issue.
