### ISSUE TITLE
Requirement Gathering

### ISSUE THREAD

**Issue by secretsayan** [oah-health/oah-health#2]
What are the features that should be included in the distribution?

**Comment by panickervinod** [comment]
Listing Few : 

a) Register RPI for with a Digital Clinic
b) Capture Patients Info (Scan & Link Aadhar Card as ID )
c) Schedule Appointments & Real Time wait time projection.
d) Generating Treatment History.
e) e-prescriptions

**Comment by secretsayan** [comment]
All the requirements are raised as new issues...Hence closing this one
